### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by cbenning** [endgameinc/eql#52]
It seems that packages are being deployed to pypi but there is no changelog, release notes, or tags in git for releases. Is it possible to have details on what has changed in each release when it happens?

**Comment by cbenning** [comment]
In addition, One example is, 0.9.8 introduced case sensitivity for certain operators. That sort of thing doesn't seem like a change that should exist in a minor version when considering semantic versioning. For us upgrading to 0.9.8 requires an overhaul of our rules.

It would be nice to have a better versioning scheme and more communication for what changes exist.

**Comment by rw-access** [comment]
You mean this? https://github.com/endgameinc/eql/blob/master/CHANGELOG.md

Hey @cbenning, none of these are breaking changes to any validation or Python EQL.
All of those are purely syntactical changes, hidden behind an undocumented opt-in parser configuration (https://github.com/endgameinc/eql/blob/157ba0b9079c013899177ace614f175b513b8999/eql/parser.py#L58).

This is for us in [elastic/detection-rules](https://github.com/elastic/detection-rules), where we use EQL for syntax and schema validation. We turn this hidden flag on, so that we can mimic how EQL is validated in Elasticsearch.

Can you point me to particular examples of queries where the expected behavior was defined and suddenly changed? I try to avoid that and respect semver, and don't want to cause any disruptions with the community or with Endgame users. If you have any examples, then that sounds like a bug and I can back some out.

Also, it might be worth noting that the major version is < 1.0.0, so it's technically less strict with semver (https://semver.org/#spec-item-4). But I still want to keep any surprises to a minimum.

**Comment by cbenning** [comment]
Interesting. I hadn't noticed the changelog, apologies. However, I am playing telephone a bit. We are digging into a specific issue which happens to be this one:

According to this: https://eql.readthedocs.io/en/latest/

`For case-insensitive equality comparisons, use the : operator. For example, process_name : "cmd.exe" is equivalent to process_name : "Cmd.exe".`

Then in 0.9.3 in the changlog:

`Internal toggle to turn off case insensitivity
 Additional tests to handle case sensitive and insensitive modes`

We are currently on 0.9.7, we cannot how to configure case sensitivity, and for some reason in 0.9.8 it seems the default changed and we have been unable to upgrade as it forces case sensitivity.

I guess the issue we're having are things we could figure out ourselves normally, but:

- There seems to be a bit of a disconnect between the changelog and the docs
- There are no release tags in git that we can use to compare versions and workaround issues
- Changing defaults can be a pretty major change.

**Comment by rw-access** [comment]
Oh, I think I understand the disconnect.

> This documentation is about EQL for Elastic Endgame. Several syntax changes were made to bring Event Query Language to the Elastic Stack:

Those syntax changes were made on the _Elasticsearch_ side, but breaking changes weren't backported. No default behavior was changed in Python EQL. There were a few cases where the behavior wasn't documented, and I either updated the documentation or might've changed something, but those should be edge cases.

I think the best actions for me (and please let me know if these aren't enough):
* Update that "Note" to say where those changes to the language were made: not in python, but in Elasticsearch
* Add GitHub tags for each patch version, and paste the relevant changelog entries into the release notes.

**Comment by cbenning** [comment]
Yes those would be very helpful for us to figure out if things are changing. Thank you.

**Comment by rw-access** [comment]
I have a PR open (https://github.com/endgameinc/eql/pull/53) to update the docs. Does that help out and is it more clear to you?

I can also go back and create GitHub releases for the 0.9.* series of releases, and add them going forward. Most changes that I've made lately are internal changes and shouldn't affect anything user-facing.
